name: Steps Outputs Workflow
on:
    workflow_dispatch:
        inputs:
            environments:
                description: deployment
                required: true
                default: dev
                type: choice
                options: 
                    - dev
                    - qa
                    - prod

            security_scans:
                description: deployment
                required: true
                default: false
                type: boolean

            smoke-test:
                description: deployment
                required: true
                type: boolean
                default: false

    pull_request:
        types:
            - "opened"
            - "reopened"
            - "closed"
            - "synchronize"
            - "ready_for_review"
        branches:
            - main
        paths:
            - "**.py"
            - "test/*"
            - "Dockerfile"
            - "requirements.txt"

    push:
        branches:
            - main
        paths:
            - "**.py"
            - "test/*"
            - "Dockerfile"
            - "requirements.txt"
            
permissions: 
    contents: read
    pull-requests: read

env:
    IMAGE_NAME: java_workflow

jobs:
    flask-docker-build:
       runs-on: ubuntu-latest
       if: ${{ inputs.environments != 'prod'}}
       outputs:
            IMAGE_NAME: ${{ steps.image.outputs.IMAGE_NAME }}
       steps:
        - name: caaling Inputs
          run: |
              echo "my environments are: ${{ inputs.environments }}
              echo "my security are: ${{ inputs.security_scans }}
              echo "my smoke test are: ${{ inputs.smoke-test }} 

        - name: check repo
          uses: actions/checkout@v7
          with:
              fetch-depth: 0

        - name: git-leaks checkpu
          uses: gitleaks/gitleaks-action@v3
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: tag
          id: tag
          run: echo "IMAGE_TAG=v${GITHUB_RUN_NUMBER}-${GITHUB_SHA::7}" >> "GITHUB_OUTPUT"

        - name: docker build 
          if: ${{ inputs.environments != 'prod'}}
          uses: docker/build-push-action@v7
          with:
              context: .
              no-cache: true
              tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.IMAGE_TAG }}
              push: false

        - id: image
          run: echo "IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.IMAGE_TAG}}" >> "$GITHUB_OUTPUT"
        - run: ${{ steps.image.outputs.IMAGE_NAME }}

    flask-docker-security:
       needs: flask-docker-build
       runs-on: ubuntu-latest
       if: ${{ inputs.environments == 'prod' && inputs. security_scans == true }}
       steps:
        - name: caaling Inputs
          run: |
              echo "my environments are: ${{ inputs.environments }}
              echo "my security are: ${{ inputs.security_scans }}
              echo "my security are: ${{ inputs.smoke-test }} 

        - name: check repo
          uses: actions/checkout@v7
          with:
              fetch-depth: 0

        - name: output of previous job
          id: image
          run: echo "${{ needs.flask-docker-build.outputs.IMAGE_NAME }}"

        - name: docker image scan secret security
          uses: aquasecurity/trivy-action@v0.36.0
          with:
              scan-type: fs
              scan-ref: ./Dockerfile
              format: "table"
              ignore-unfixed: "true"
              vuln-type: "os.library"
              scanners: "secrets"
              severity: "CRITICAL"
              exit-code: "1"

        - name: docker image scan vuln security
          uses: aquasecurity/trivy-action@v0.36.0
          with:
              image-ref: ${{ needs.flask-docker-build.outputs.IMAGE_NAME }}
              format: "table"
              ignore-unfixed: "true"
              vuln-type: "os.library"
              scanners: "vuln"
              severity: "CRITICAL"
              exit-code: "1"

    flask-deploy:
        needs:
          - flask-docker-build
          - flask-docker-security
        runs-on: ubuntu-latest
        if: ${{ inputs.environments == 'prod' && inputs.smoke-test == true}}
        steps: 
            - name: calling Inputs
              run: |
                  echo "my environments are: ${{ inputs.environments }}
                  echo "my security are: ${{ inputs.security_scans }} 
                  echo "my s=smoke test are: ${{ inputs.smoke-test }} 

            - name: calling output of previous job
              run: echo "${{ needs.flask-docker-build.outputs.IMAGE_NAME }}"

            - name: image validation
              shell: bash
              run: |
                  if [[ -z "${{ needs.flask-docker-build.outputs.IMAGE_NAME }}" ]]; then
                  echo "image not present, and is required"
                  exit 1
                  else
                  echo "image present; "${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${GITHUB_SHA::7}"
                  fi

            - name: docker network
              run: docker network create --driver=bridge mynetworks

            - name: docker container run
              run: |
                  docker run -d -p 8080:80 \
                  --network mynetworks \
                  --name myreact \
                  ${{ needs.flask-docker-build.outputs.IMAGE_NAME }}

            - name: container smoke test
              run: |
                  curl --fail --show-errors http://localhost:8080 || true
                  curl --fail --show-errors http://localhost:8080/health || true

            - name: container failure
              if: ${{ failure() }}
              run: docker logs myreact || true

            - name: container remove
              if: ${{ always() }}
              run: docker rm -f myreact || true

            - name: docker login
              uses: docker/login-action@v4
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: docker image push 
              run: docker push ${{ needs.flask-docker-build.outputs.IMAGE_NAME }}